#!/usr/bin/env bash
#this script will display information about subdomains.

if [ -z "$2" ]; then
subs=("www.$1" "lb-01.$1" "web-01.$1" "web-02.$1")
for sub in ${subs[@]}; do
dig $sub | awk '/ANSWER SECTION:/ { getline; split($1, a, "."); print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
done
else :
sub=$2.$1
dig $sub | awk '/ANSWER SECTION:/ { getline; split($1, a, "."); print "The subdomain", a[1], "is a", $4, "record and points to", $5}'
fi
